server:
  port: 9090
spring:
  application:
    name: search-api
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  flyway:
    baselineOnMigrate: true
    locations: classpath:/db/migration
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace